create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room text not null check (char_length(room) between 1 and 48),
  sender text not null check (sender in ('student', 'teacher')),
  sender_name text not null check (char_length(sender_name) between 1 and 30),
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists messages_room_id_idx
  on public.messages (room, id);

alter table public.messages enable row level security;

drop policy if exists "Anyone can read chat messages" on public.messages;
create policy "Anyone can read chat messages"
  on public.messages for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can send chat messages" on public.messages;
create policy "Anyone can send chat messages"
  on public.messages for insert
  to anon, authenticated
  with check (
    room = 'kim-math'
    and sender in ('student', 'teacher')
    and char_length(sender_name) between 1 and 30
    and char_length(body) between 1 and 1000
  );
